# Generated by Django 5.2 on 2026-01-07 03:16

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_district_alter_listing_room_type_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='professions',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='services',
        ),
        migrations.AddField(
            model_name='listing',
            name='professions',
            field=models.ManyToManyField(blank=True, to='listings.subject'),
        ),
        migrations.AddField(
            model_name='listing',
            name='services',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Services'),
        ),
    ]
